apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dhis2-core-helm.fullname" . }}
data:
  dhis-google-auth.json: |
{{ tpl (.Files.Get "config/dhis-google-auth.json") . | indent 4 }}
  dhis.conf: |+
    {{- .Files.Get "config/dhis.conf" | indent 4 }}
  log4j2.xml: |
    {{- .Files.Get "config/log4j2.xml" | nindent 4 }}
  server.xml: |
    {{- .Files.Get "config/server.xml" | nindent 4 }}

