apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-database-credentials"
  namespace: "{{ .Release.Namespace }}"
data:
  username: {{ .Values.dhis2.db.username | b64enc }}
  password: {{ .Values.dhis2.db.password | b64enc }}
type: Opaque

